### ISSUE TITLE
GUI is not shown

### ISSUE THREAD

**Issue by Fangjunfan123** [matjesg/deepflash2#51]
The GUI was not shown, when run the jupyter notebook cell No.2. Here is my log. 
50 ERROR deepflash2.gui list assignment index out of range
Traceback (most recent call last):
  File "C:\Users\fangj\.conda\envs\image\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\fangj\AppData\Local\Temp\ipykernel_22724\64341330.py", line 5, in <module>
    t = GUI(path);
  File "C:\Users\fangj\.conda\envs\image\lib\site-packages\deepflash2\gui.py", line 1360, in __init__
    self.gt = GTEstUI(hide=True, path=self.proj_path, config=self.config)
  File "C:\Users\fangj\.conda\envs\image\lib\site-packages\deepflash2\gui.py", line 595, in __init__
    self.sb_acc.set_title(i, name)
  File "C:\Users\fangj\.conda\envs\image\lib\site-packages\ipywidgets\widgets\widget_selectioncontainer.py", line 69, in set_title
    titles[index]=title
IndexError: list assignment index out of range

**Comment by Fangjunfan123** [comment]
It seems Installing ipywidget=7.7.2 can solve the problem.
